<a href="https://colab.research.google.com/github/chanikansuksen/data_viz_2022/blob/main/Data_Structure(complete).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลาย ๆ ตัวไว้ด้วยกันอย่างเป็นระเบียบ

## ```list ( )```
- เก็บอะไรก็ได้
- ลำดับในการเก็บ มีความสำคัญ

In [ ]:
list_a = [ 1, 2, 3, 4, 5, 6]   # [ ] square brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = [ 'ab', 2, 3.14, list_a]

In [ ]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list

In [ ]:
list_a [3]

4

In [ ]:
list_b [3] #เริ่มนับตัวแรกเป็นตัวที่ศูนย์ หนึ่ง สอง สาม ไปเรื่อย ๆ

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][4]  # เอาตัวที่ 4 จากlist_b[3]

5

In [ ]:
list_a[6]

IndexError: ignored

In [ ]:
list_a[-1]  # index -1 คือตัวสุดท้ายของ list

6

In [ ]:
list_a[-4]  # index ติดลบคือนับจากตัวท้ายมาหน้า

3

### การสร้าง  ```list ()```

In [ ]:
list_x1 = [] #แบบที่ 1
list_x2 = list()  #แบบที่ 2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเขาไปใน list ด้วย  ```append () ```

In [ ]:
list_x1.append(2)

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [ ]:
list_x1[0]

2

In [ ]:
list_x1[-1]

4

In [ ]:
list_x2 

[]

In [ ]:
list_x2.append('ha')

In [ ]:
list_x2

['ha', 'ha']

### ลบสมาชิกจาก list

In [ ]:
list_x1.append( 'ha' )

In [ ]:
list_x1

[2, 4, 'ha', 'ha']

In [ ]:
list_x1.pop()  # คำสั่ง pop ใช้เพื่อลบไล่จากท้ายมาหน้า เนื่องจากรัน pop ไปสี่ครั้ง จึงทำให้ ha หายไป

2

In [ ]:
list_x1.append(2)

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4)

In [ ]:
list_x1

[2, 3, 4]

In [ ]:
list_x1.pop()

4

In [ ]:
list_x1

[2, 3]

In [ ]:
list_x1.pop()

3

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4)

In [ ]:
list_x1

[2, 4]

###  ``` len()``` ตรวจสอบจำนวนสมาชิกของ list


In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)

6

### string is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10]

' '

In [ ]:
len(st_stat)

44

### List Slicing

``` list [จุดเริ่มต้น : จุดสุดท้าย (โปร่ง)] ```

``` list [จุดเริ่มต้น : จุดสุดท้าย (โปร่ง) : step]```

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

####``` : colon ```

In [ ]:
list_a[-3:]  # : colon

[4, 5, 6]

In [ ]:
list_a[: 4]  # : colon

[1, 2, 3, 4]

In [ ]:
list_a[1:4]

[2, 3, 4]

In [ ]:
list_a[:]

[1, 2, 3, 4, 5, 6]

#### step

In [ ]:
list_c = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2] # จุดสุดท้ายที่ 10 แต่ step คือ 2

[1, 3, 5, 7, 9]

In [ ]:
list_c[: : -1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

###  ```range ()```


In [ ]:
range (21) #คืออยากได้ 21 ตัวโดยเริ่มที่0

range(0, 21)

In [ ]:
a = list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list(range(1,21)) #จุดเริ่มต้นที่1 แต่21 เป็นวงกลมโปร่ง

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

- 12 : 30 : 15
- 13 : 41 : 07
- 09 : 11 : 50
- 21 : 30 : 15
- 03 : 10 :15

In [ ]:
#01 : 00 : 00

a = 1*60*60
print (a)

3600


In [ ]:
#01 : 02 : 03

a = (1*60*60) + (2*60) + 3
print(f' 01:02:03 แปลงเป็นวินาที ได้ {a} วินาที')

 01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที



``` ▶ กำหนดให้ ◀ ```

☑ p แทนจำนวนชั่วโมงที่แปลงเป็นเป็นวินาที

☑ q แทนจำนวนนาทีที่แปลงเป็นเป็นวินาที

☑ r แทนจำนวนวินาที


In [ ]:
p = 60*60
q = 60
r = 1

In [ ]:
p

3600

In [ ]:
q

60

In [ ]:
r

1

In [ ]:
# ข้อ 1 ;  12 : 30 : 15

dy = '12 : 30 : 15'.split(':')  # สร้างตัวแปรที่ใช้เก็บข้อมูล และใช้คำสั่ง split : เพื่อแยก string
ty = int(dy[0])*int(p) + int(dy[1])*int(q)+ int(dy[2])*int(r)  # เมื่อแยก string แล้ว นำข้อมูลที่เป็น string ทั้งในส่วนของตัวแปรและข้อมูลที่กำหนดให้ให้เป็น int ก่อน 
# เมื่อแปลงเป็นข้อมูลทั้งสองส่วนเป็น int แล้ว นำมาคูณกัน
print(f' 12 : 30 : 15 แปลงเป็นวินาที ได้ {ty} วินาที') #print ผลลัพธ์ที่ได้ ให้ออกมาเป็นข้อความ

 12 : 30 : 15 แปลงเป็นวินาที ได้ 45015 วินาที


In [ ]:
# ข้อ 2 ; 13 : 41 : 07
rt = '13 : 41 : 07'.split(':')
yd = int(rt[0])*int(p) + int(rt[1])*int(q)+ int(rt[2])*int(r)
print(f' 13 : 41 : 07 แปลงเป็นวินาที ได้ {yd} วินาที')

 13 : 41 : 07 แปลงเป็นวินาที ได้ 49267 วินาที


In [ ]:
# ข้อ 3 ; 09 : 11 : 50
yj = '09 : 11 : 50'.split(':')
sb = int(yj[0])*int(p) + int(yj[1])*int(q)+ int(yj[2])*int(r)
print(f' 09 : 11 : 50 แปลงเป็นวินาที ได้ {sb} วินาที')

 09 : 11 : 50 แปลงเป็นวินาที ได้ 33110 วินาที


In [ ]:
# ข้อ 4 ; 21 : 30 : 15
jk = '21 : 30 : 15'.split(':')
sh = int(jk[0])*int(p) + int(jk[1])*int(q)+ int(jk[2])*int(r)
print(f' 21 : 30 : 15 แปลงเป็นวินาที ได้ {sh} วินาที')

 21 : 30 : 15 แปลงเป็นวินาที ได้ 77415 วินาที


In [ ]:
# ข้อ 5 ; 03 : 10 : 15
jy = '03 : 10 : 15'.split(':')
js = int(jy[0])*int(p) + int(jy[1])*int(q )+ int(jy[2])*int(r)
print(f' 03 : 10 : 15 แปลงเป็นวินาที ได้ {js} วินาที')

 03 : 10 : 15 แปลงเป็นวินาที ได้ 11415 วินาที


## Dictionary

- คล้าย list ()
- index เป็นอะไรก็ได้ ไม่จำำ้ป็นต้องเป็นตัวเลขลลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

In [2]:
dict_a = {1: 'Happy', 'N': 'New', '2022': 'Year'}  # { } curly brackets

### การชี้สมาชิกใน Dictionary

In [3]:
dict_a[1]

'Happy'

In [5]:
dict_a['N']

'New'

In [6]:
dict_a['2022']

'Year'

In [10]:
dict_a.keys() # เรียกดู keys ว่ามีอะไรบ้าง

dict_keys([1, 'N', '2022'])

In [9]:
dict_a.values() # เรียกดู value ว่ามีค่าอะไรบ้าง

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [11]:
dict_a[7] = 3.14

In [12]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [13]:
dict_a['N'] = 'NNNNEEEEWWWW'

In [15]:
dict_a # ถ้าเราใช้ index ซ้ำ มันก็จะไปอัปเดต index ใหม่แทนที่อันเก่า

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

## Numpy Array


- เก็บได้แต่ตัวเลข (ไม่รู้ว่าเก็บโครงสร้างสองมิติ สามมิติเป็นตัวหนังสือไปเพื่ออะไร)
- อ้างอิงโดยใช้ พิกัด ( 2มิติ ก็มองเป็น Metrix )

In [16]:
import numpy

1D array

In [24]:
list_A = [1, 2, 3, 4, 5]

In [26]:
arr_a = numpy.array ([list_A])

In [27]:
arr_a

array([[1, 2, 3, 4, 5]])

In [30]:
list_A

[1, 2, 3, 4, 5]

In [28]:
arr_a[0]

array([1, 2, 3, 4, 5])

In [29]:
list_A[0]

1

In [32]:
5*arr_a # Metrix  ( scalar multiplication )

array([[ 5, 10, 15, 20, 25]])

In [34]:
5*list_A  #ทำซ้้ำ 5 รอบ

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [35]:
arr_b = numpy.array([5, 10, 15, 20, 25])

In [36]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [38]:
arr_b =numpy.array([10, 20, 30, 40, 50])

In [39]:
print(arr_a)

[[1 2 3 4 5]]


In [40]:
arr_a+arr_b

array([[11, 22, 33, 44, 55]])

In [49]:
arr_a.shape

(1, 5)

2D array

In [41]:
import numpy as np

In [44]:
arr2_z = np.array([[1, 2, 3] , [4, 5, 6]])

In [46]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr2_z.shape

(2, 3)

###  ```np.zeros ()```



In [51]:
arr2_3_5_0 = np.zeros((3,5))

In [52]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
arr2_3_5_0[1,2] = 9 # กำหนดค่า

In [57]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
arr2_3_5_0[1,2]  #ชี้

9.0

In [59]:
print(list_A)  # เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


### ```np.ones()```



In [62]:
arr_2_4_5_1 = np.ones((4,5))

In [63]:
arr_2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
arr_2_4_5_200 = 200*np.ones((4,5))

In [67]:
arr_2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Metrix Operation

#### การบวก ลบ matrix

In [80]:
arr_2_4_5_200 + arr_2_3_5_0  # การบวก ลบ matrix shape ต้องเท่ากัน

NameError: ignored

In [69]:
arr_2_4_5_200 + arr_2_4_5_1

array([[400., 400., 400., 400., 400.],
       [400., 400., 400., 400., 400.],
       [400., 400., 400., 400., 400.],
       [400., 400., 400., 400., 400.]])

In [79]:
5*arr_a # Matrix ( scelar multiplication)

array([[ 5, 10, 15, 20, 25]])

#### การคูณ Matrix
- $aM$ scelar คูณ Matrix ( scalar คูณกระจายเข้าไปทุกตัวของ Matrix )
- $M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)

$aM$

$M\times N$ ( dot product )
- ( m, n ) $\times$ ( n, o ) = ( m, o ) (shape)

In [71]:
mat_a = np.array([[2, 3, 5] , [4, 6, 7]])
mat_b = np.array([[1, 2, 5] , [2, 4, -7]])
mat_c = np.array([[2, 3] , [4, 6] , [7, 9]])

In [72]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [73]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [74]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

In [75]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [76]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

In [77]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [78]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [82]:
mat_a * mat_b  # คูณด้วยตำแหน่งเดียวกัน ไม่ใช่การคูณแบบ Matrix

array([[  2,   6,  25],
       [  8,  24, -49]])

#### Matrix Slicing

In [83]:
mat_X[:2,:2]

NameError: ignored

HW 3

1. สร้าง array ที่เป็นรูปต้น christmas

2. slice เลข 1 ออกจาก array HW3 ด้วย slice แค่ครั้งเดียว

In [84]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Pandas Dataframe ( แยกออกไปเป็น Notebook เฉพาะ )